[package]
name = "entities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roll_dice = {path = "../roll_dice"}
narratives = {path = "../narratives"}
sqlite = "0.30.4"
eframe = "0.21.3"
