[package]
name = "libtext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.0"
whisper-rs = "0.4.0"
narratives = {path = "../narratives"}
log = "0.4.17"
cpal = "0.15.0"
